############################################################
# RiboLongShort configuration file
# Edit only this file before running the pipeline.
############################################################

project_name: "PROJECT_NAME"
project_description: "Ribo-seq project"

project_root: "/path/to/project"
resources_dir: "/path/to/resources"

threads: 20

references:
  genome_fasta: "GRCh38.primary_assembly.genome.fa"
  gtf: "gencode.v45.annotation.gtf"
  star_index: "hg38_star_index"
  contaminant_index: "rnas_dictionary/indexes/bowtie1/rnas_dictionary_human"

size_modes:
  - "all_lengths"
  - "28_36"

samples:
  - run_id: "RUN_ACCESSION_1"
    sample_name: "sample_1"

  - run_id: "RUN_ACCESSION_2"
    sample_name: "sample_2"

reports:
  multiqc_name: "RiboLongShort_MultiQC.html"
  qc_summary_name: "RiboLongShort_QC_report.tsv"
