############################################################
# RiboLongSmORF configuration file
# Edit only this file before running the pipeline.
############################################################

project_name: "PROJECT_NAME"

project_description: >
  Ribo-seq project

project_root: "/path/to/project_root"

threads: 20

size_modes:
  - "all_lengths"
  - "28_36"

cutadapt:
  mode: "interactive"
  default_remove_5prime_nt: 3
  default_polyA: "A{10}"
  minimum_length: 17

filtering:
  remove_N: true
  remove_polyG_only_reads: true
  rpf_min_length: 28
  rpf_max_length: 36

samples:
  - run_id: "RUN_ACCESSION_1"
    sample_name: "sample_1"
    condition: "condition_1"
    replicate: "Rep1"

  - run_id: "RUN_ACCESSION_2"
    sample_name: "sample_2"
    condition: "condition_1"
    replicate: "Rep2"

tools:
  run_ribotricer: true
  run_iribo: false
