############################################################
# GLOBAL SETTINGS
############################################################

project_root: "/path/to/project_root"
threads: 20

environment:
  name: "ribo_env"
  file: "environment.yml"

adapters: "illumina_adapters.txt"
